name: Setup & Install
description: Common setup steps for Actions

inputs:
  registry-url:
    description: package registry url
    required: false
    default: https://registry.npmjs.org


runs:
  using: composite
  steps:
    - name: Install PNPM
      uses: pnpm/action-setup@v4

    - name: Install Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
        cache: pnpm
        registry-url: ${{ inputs.registry-url }}

    - name: Install Dependencies
      shell: bash
      run: pnpm install --ignore-scripts --frozen-lockfile
