name: Setup & Install
description: Common setup steps for Actions

runs:
  using: composite
  steps:
    - name: Install PNPM
      uses: pnpm/action-setup@v4

    - name: Install Node.js
      uses: actions/setup-node@v5
      with:
        node-version-file: '.nvmrc'
        cache: pnpm

    - name: Install Dependencies
      shell: bash
      run: pnpm install --ignore-scripts --frozen-lockfile
