name: Setup & Install

on: workflow_call

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Install PNPM
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install
